---
language: node_js
node_js:
  - "6"
  - "10"

sudo: false

cache:
  yarn: true


install:
  - yarn install --no-lockfile

branches:
  only:
    - master
    - beta
    - release
    - auto
    - /^greenkeeper.*$/

before_deploy:
  - npm install -g auto-dist-tag
  - auto-dist-tag --write

deploy:
  provider: npm
  email: stefan.penner+ember-cli@gmail.com
  api_key:
    secure: ONrQEBodMvUB0lBZfxq0THahoQNqU5I9Je7+NcPoP+DE5X0zgzZNNosX2CMiVsqZQ6mv4lgUOkYxaW7HlqS1v35sHYGPd7xcx7QXW6iaTwniFK/wryPzLjNrMsbzSMei8hzyH6fyXNd5pKE7AeLf3nV3ehklusS0l/mPRhltTks=
  on:
    tags: true
    repo: ember-cli/ember-cli-version-checker
